/**
 * APIS Integration Dialer Catix4
 * Documentação APIS - Dialer Catix4 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: desenvolvimento@optjuntos.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { CampaignsContactCallsResultDados } from './campaignsContactCallsResultDados';


export interface CampaignsContactCallsResult { 
    result?: boolean;
    dados?: CampaignsContactCallsResultDados;
}