/**
 * APIS Integration Dialer Catix4
 * Documentação APIS - Dialer Catix4 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: desenvolvimento@optjuntos.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CampaignsContact { 
    /**
     * Id Campanha
     */
    campaignUuid?: number;
    /**
     * Id CRM Cliente Integração
     */
    crmPeopleId?: number;
    /**
     * Nome do Contato
     */
    campaignsContactName?: string;
    /**
     * Opcional
     */
    campaingsContactSheetText1?: string;
    /**
     * Opcional
     */
    campaingsContactSheetText2?: string;
    /**
     * Opcional
     */
    campaingsContactSheetText3?: string;
    /**
     * Opcional
     */
    campaingsContactSheetText4?: string;
    /**
     * Opcional
     */
    campaingsContactSheetText5?: string;
}