/**
 * APIS Integration Dialer Catix4
 * Documentação APIS - Dialer Catix4 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: desenvolvimento@optjuntos.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CampaignsContactCallsResultDados { 
    /**
     * Autoincremental
     */
    campaignsContactCallUuid?: number;
    /**
     * Id Tabela campaigns_contacts
     */
    campaignsContactUuid?: number;
    /**
     * Id Tabela campaigns
     */
    campaignUuid?: number;
    /**
     * Id CRM Cliente Integração
     */
    crmPeopleId?: number;
    /**
     * Telefone Contato
     */
    campaignsContactName?: string;
    /**
     * Autoincremental
     */
    createdAt?: string;
    /**
     * Autoincremental
     */
    updatedAt?: string;
}